name: Generate ARM Template from Bicep

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generateFile:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Bicep build
        run: |
          curl -Lo bicepinstall
          https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help

      - name: Run Bicep build
        run: |
          bicep build deploy/main.bicep
          ls -l deploy/*.json
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save ARM Template
          skip_checkout: true
